version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      # Anonymize node_modules to prevent local host system from overriding the container's linux dependencies
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # Enable polling for hot-reloading on Windows WSL/Hyper-V setups
      - WATCHPACK_POLLING=true
